const express=require('express')//import expess
 const router=new express.Router()//create router
 const userController=require('../Controller/userController')
 const adminController=require("../Controller/adminController")
 const adminEventController=require('../Controller/adminEventController')
 const userBooking=require('../Controller/userBooking')
 const jwtmiddleware=require("../Middlewares/jwtMiddleware")
 const multerConfig=require('../Middlewares/multerMiddleware')
const jwtMiddleware = require('../Middlewares/jwtMiddleware')
const userMiddleware=require('../Middlewares/userMiddleware')
 router.post('/register',userController.userRegister)
 router.post('/login',userController.userLogin)
 router.post('/adminReg',adminController.adminReg)
 router.post('/adminLogin',adminController.Adminlogin)
 router.post('/addEvent',jwtmiddleware,multerConfig.single('eventImage'),adminEventController.addEvents)
router.get("/getarts",adminEventController.GetArt)
router.get("/getmusic",adminEventController.GetMusic)
router.get("/getallEvent",adminEventController.GetallEvent)
router.put('/update/:eid',jwtmiddleware,multerConfig.single('eventImage'),adminEventController.UpdateEvent)
router.delete('/delete/:eid',jwtMiddleware,adminEventController.delete)
router.post("/bookTticket/:eid",userMiddleware,userBooking.bookEvent)
router.post("/paymentsuccess",userBooking.paymentsuccess)
router.get('/allBookings',userBooking.GetallBooking)
router.get('/userbookings/:reqBody',userBooking.getUserBooking)
 module.exports=router
